# Content for the service pages. Case study cards reference CASES keys.
CAL = "https://calendly.com/munmun_mnstudio/lets_get_to_know_each_other"
WA = "https://wa.me/919099344578"

CASES = {
    "flowmo": ("FlowMo", "EdTech · 0-to-1", "$600K", "raised from VCs for the in-app LMS we designed from zero to one.", "../case-studies/flowmo.html"),
    "resultbook": ("Resultbook", "Social impact · Enterprise", "2nd", "flagship product for Vera Solutions, connecting impact investors with NGOs.", "../case-studies/resultbook.html"),
    "freedai": ("Freed AI", "Healthcare AI · UX discovery", "10,000+", "clinicians use the AI scribe we explored a browser extension for.", "../case-studies/freedai.html"),
    "reunion": ("Reunion", "Clean energy · Marketplace", "$8B+", "in tax credits transferred through the marketplace we designed.", "../index.html#case-studies"),
    "surreal": ("Surreal", "E-commerce · CRO", "+150%", "revenue per user within a week of launch.", "../index.html#case-studies"),
    "space": ("Space", "Audio SaaS · B2B", "+18.1%", "MRR for a Clubhouse-style audio platform.", "../index.html#case-studies"),
    "iseechange": ("I See Change", "Climate tech · Research", "White House", "among the stakeholders we interviewed for a new EV charging feature.", "../index.html#case-studies"),
    "go2andaman": ("Go2Andaman", "Travel · Redesign", "Ferry booking", "experience redesigned for more conversions.", "../index.html#case-studies"),
    "collagerie": ("Collagerie", "Retail · AI search", "AI search", "Redefining product discovery with an AI-based search experience.", "../index.html#case-studies"),
    "mentorship": ("Mentorship platform", "EdTech · Growth", "+884%", "monthly recurring revenue, with 425% more paying customers.", "../index.html#results"),
}

ENGAGE = [
    ("Fractional", "Senior product design and leadership inside your team, part-time, for as long as you need it."),
    ("Advisory", "Focused guidance at the decisions that matter: audits, roadmap reviews and design critiques."),
    ("Retainer", "Ongoing design and product support with a team that already knows your product."),
]

# slug, group label, menu title, short title for "other services"
PAGES = [
  dict(slug="impact-startups", group="Who we solve for", name="For Impact-Driven Startups",
    title="Impact-driven startups — MN Studio",
    meta="Founding MVPs and flagship launches for impact-driven startups and organisations. Data-heavy products, platforms and software, industry agnostic.",
    h1='From first idea to <span class="accent">flagship product.</span>',
    lede="For founders going from zero to one, and for enterprises launching a new flagship product. We design data-heavy products, platforms and software that people actually want to use, whatever the industry.",
    problem_h='Big mission, <span class="accent">small runway.</span>',
    problem=["Impact-driven teams rarely have time to waste. You need a product that proves the idea to users, funders and your board, and you need it without building the wrong thing first.",
             "We bring the product thinking and design craft of a senior in-house team, from the first interviews to a launch-ready product, so you can ship with confidence and keep momentum."],
    get_h='What we <span class="accent">bring.</span>',
    get=[("Founding MVP", "Zero-to-one design, from first concept to a launch-ready v1."),
         ("Flagship launches", "New products for established organisations, designed to sit next to what already works."),
         ("Data-heavy UX", "Dashboards, profiles and reporting that make complex data easy to act on."),
         ("A team that stays", "Fractional and retainer support after launch, so the product keeps improving.")],
    steps=[("Kick off", "Interviews"), ("Stage 1", "Research, UX & discovery workshops"), ("Stage 2 · Go / no go", "Testing"), ("Stage 3", "UI design"), ("Launch", "Testing & handover")],
    cases=["flowmo", "resultbook", "reunion"],
    faq=[("Do you only work with nonprofits?", "No. We work with any team building for impact: startups, social enterprises, NGOs and enterprises launching a new product. We're industry agnostic."),
         ("We already have a product. Can you still help?", "Yes. We also design flagship launches for established organisations and run UI/UX overhauls for products already in market."),
         ("Do you work with our developers?", "Yes. We design with your engineers from day one and hand over a design system and components they can build from.")],
    related=["founding-mvp", "full-stack-design", "giving-back"]),

  dict(slug="vc-private-equity", group="Who we solve for", name="For VC & Private Equity",
    title="VC & private equity — MN Studio",
    meta="Product design and consultation for venture capital and private equity firms: in-house tools and hands-on support for portfolio startups.",
    h1='Structure for the chaos, <span class="accent">across your portfolio.</span>',
    lede="In-house tools for your firm, and hands-on support for portfolio startups working through ambiguity and chaos. We bring the structure, clarity and product consultation that gets teams shipping again.",
    problem_h='When a portfolio company <span class="accent">stalls.</span>',
    problem=["Portfolio companies often hit the same wall: an unclear roadmap, a product that's drifted from its users, or a team without senior design and product leadership.",
             "We step in quickly, assess where the product stands, and give founders a clear plan and the hands to deliver it. For your firm, we design the internal tools your team relies on every day."],
    get_h='How we <span class="accent">help.</span>',
    get=[("Portfolio support", "Product audits, roadmaps and design for portfolio startups that need structure."),
         ("In-house tools", "Internal platforms for your firm: deal flow, portfolio reporting and data tools."),
         ("Interim leadership", "Fractional design and product leaders while a company hires."),
         ("Alignment workshops", "Sessions that get founders, teams and investors agreeing on what matters.")],
    steps=[("Assess", "Product & team"), ("Plan", "Prioritised roadmap"), ("Embed", "Design & lead"), ("Report", "Back to the firm")],
    cases=["reunion", "flowmo", "resultbook"],
    faq=[("Can you work across several portfolio companies?", "Yes. Many firms use us as a shared product and design resource, moving between companies as priorities change."),
         ("Who do we work with day to day?", "Munmun, the founder, leads every engagement, with designers and product managers added as the work needs."),
         ("How quickly can you start?", "Usually within a couple of weeks. Book a call and we'll tell you honestly what's possible.")],
    related=["product-management", "leadership", "ux-overhauls"]),

  dict(slug="founding-mvp", group="What we design", name="Founding MVP",
    title="Founding MVP design — MN Studio",
    meta="Zero-to-one product design for founders: research, UX, UI and a design system, from first concept to a launch-ready v1.",
    h1='A first version <span class="accent">worth launching.</span>',
    lede="Zero-to-one product design, from first concept to a launch-ready v1: research, UX, UI and a design system your engineers can build from. The goal is a product people actually want to use, and one you can sell.",
    problem_h='Build the right thing, <span class="accent">first.</span>',
    problem=["The most expensive MVP is the one nobody needs. We test ideas, strategy and assumptions at every stage so what you launch is aligned with what users actually need.",
             "As an MVP, 0-to-1 design firm, we build on proven UI components rather than reinventing them. It helps ship faster and shortens the time to market."],
    get_h='What you <span class="accent">get.</span>',
    get=[("Discovery", "User interviews, workshops and a clear definition of the first version."),
         ("Flows & wireframes", "Multiple user flows, tested before any pixels are polished."),
         ("UI & prototype", "Custom branding and UI, with clickable prototypes for users and investors."),
         ("Design system", "Components your engineers can build from, on top of proven UI libraries.")],
    steps=[("Kick off", "Interviews"), ("Stage 1 · Demo day", "Research, UX & discovery workshops"), ("Stage 2 · Go / no go", "Testing"), ("Stage 3 · Demo day", "UI design"), ("Launch", "Testing")],
    cases=["flowmo", "resultbook", "reunion"],
    faq=[("How long does an MVP take?", "It depends on scope. We'll give you a realistic plan after a first call and a short discovery."),
         ("Do you build the product too?", "We design it and work side by side with your engineers. With spec-driven tools like Kiro, Cursor and Claude Code, and Replit for rapid prototypes, we can also turn designs into working prototypes fast."),
         ("Can you help us raise?", "We design products investors want to invest in. FlowMo, an MVP we designed, went on to raise $600K from VCs.")],
    related=["impact-startups", "full-stack-design", "agentic-workflows"]),

  dict(slug="agentic-workflows", group="What we design", name="Agentic Workflows",
    title="Agentic workflow design — MN Studio",
    meta="AI-native product design: agentic workflows designed around how people actually work, so automation earns trust instead of adding friction.",
    h1='AI that fits <span class="accent">how people work.</span>',
    lede="We design agentic workflows and AI-native flows around how people actually work, so automation earns trust instead of adding friction.",
    problem_h='Automation people <span class="accent">actually trust.</span>',
    problem=["Adding AI to a product is easy. Making it useful is not. People need to understand what the AI did, correct it when it's wrong, and stay in control of the result.",
             "We map the real workflow first, then design where AI should act, where it should suggest, and where a person needs to decide."],
    get_h='What we <span class="accent">design.</span>',
    get=[("Workflow mapping", "Where people spend time today, and which steps an agent can take on."),
         ("Human in the loop", "Review, edit and approve patterns that keep people in control."),
         ("AI interfaces", "Prompts, suggestions, summaries and generated content that are easy to trust."),
         ("Spec-driven builds", "Specs and prototypes built with Kiro, Cursor and Claude Code.")],
    steps=[("Map", "Current workflow"), ("Find", "Where AI helps"), ("Design", "Human-in-the-loop flows"), ("Prototype", "Test with real users")],
    cases=["freedai", "collagerie", "flowmo"],
    faq=[("Do we need an AI product already?", "No. We often start with an existing workflow and find where AI can take work off people's plates."),
         ("Which AI tools do you use?", "We work with spec-driven development in Kiro, Cursor and Claude Code, rapid prototyping in Replit, and whichever models your team uses."),
         ("How do you handle AI mistakes?", "We design for them: clear sources, easy edits, and a person approving anything that matters.")],
    related=["founding-mvp", "full-stack-design", "ux-overhauls"]),

  dict(slug="ux-overhauls", group="What we design", name="UI/UX Overhauls",
    title="UI/UX overhauls — MN Studio",
    meta="Audits, redesigns and optimisation of products already in market. We find what's slowing users down and fix it, without starting over.",
    h1='Fix what’s slowing <span class="accent">your users down.</span>',
    lede="Audits, redesigns and optimisation of products already in market. We find what's getting in your users' way and fix it, without throwing away what already works.",
    problem_h='Products drift. <span class="accent">We bring them back.</span>',
    problem=["Years of features, quick fixes and new hires leave most products harder to use than they need to be. Users feel it long before the metrics show it.",
             "We review your product across research, UX, UI and the roadmap behind it, then redesign the parts that matter most, in the order that pays off fastest."],
    get_h='What you <span class="accent">get.</span>',
    get=[("UX audit", "A clear, prioritised list of what's hurting users and why."),
         ("Redesign", "New flows and UI for the parts that matter most."),
         ("Design system", "Consistent components so the product stays tidy after we leave."),
         ("Measurable goals", "Agreed metrics before we start, so you can see what changed.")],
    steps=[("Audit", "Research, UX & UI review"), ("Prioritise", "What to fix first"), ("Redesign", "Flows & UI"), ("Test", "With real users"), ("Ship", "Alongside your team")],
    cases=["go2andaman", "surreal", "space"],
    faq=[("Do we have to redesign everything?", "Rarely. Most of the value comes from fixing a handful of key flows well."),
         ("Can you work with our existing design system?", "Yes. We extend what you have where we can, and only replace what's holding you back."),
         ("What does an audit include?", "A review of research, UX, UI and the roadmap, delivered as a prioritised plan written for your whole team.")],
    related=["cro-ecommerce", "full-stack-design", "product-management"]),

  dict(slug="cro-ecommerce", group="What we design", name="CRO for E-commerce",
    title="CRO design for e-commerce — MN Studio",
    meta="Conversion-focused design for online stores and websites. For Surreal, revenue per user rose 150% within a week of launch.",
    h1='More revenue from <span class="accent">the traffic you have.</span>',
    lede="Conversion-focused design for online stores and websites. For Surreal, revenue per user rose 150% within a week of launch.",
    problem_h='Every step is a chance <span class="accent">to lose a sale.</span>',
    problem=["Shoppers leave for small reasons: a confusing product page, a surprise at checkout, a slow path to the thing they came for.",
             "We use your analytics and session recordings to find where buyers drop off, then redesign those moments and measure the result."],
    get_h='What we <span class="accent">optimise.</span>',
    get=[("Product pages", "Clear value, better imagery and fewer reasons to hesitate."),
         ("Cart & checkout", "Fewer steps and fewer surprises between add to cart and paid."),
         ("Navigation & search", "Faster paths to the right product."),
         ("Measurement", "Hotjar, Mixpanel and Google Analytics to prove what worked.")],
    steps=[("Analyse", "Funnels & recordings"), ("Hypothesise", "Where buyers drop off"), ("Design", "Conversion-focused pages"), ("Launch", "And measure")],
    cases=["surreal", "go2andaman", "collagerie"],
    faq=[("Which platforms do you work with?", "We design for any storefront or custom build, and hand over designs your developers can ship."),
         ("How soon will we see results?", "It depends on your traffic. Surreal saw a 150% lift in revenue per user within a week of launch."),
         ("Do you run A/B tests?", "We can design variants for testing and help you read the results with your analytics tools.")],
    related=["ux-overhauls", "full-stack-design", "founding-mvp"]),

  dict(slug="full-stack-design", group="How we lead", name="Full-Stack Product Design",
    title="Full-stack product design — MN Studio",
    meta="Research, UX, UI and design systems, end to end. One team from the first interview to the last component.",
    h1='Research to design system, <span class="accent">end to end.</span>',
    lede="Research, UX, UI and design systems, end to end. One team from the first interview to the last component, so nothing gets lost between hand-offs.",
    problem_h='One team, <span class="accent">no gaps.</span>',
    problem=["When research, UX and UI are split across people and agencies, insights get lost and products feel stitched together.",
             "We cover the whole design stack, so what we learn in interviews shows up in the flows, the UI and the components your engineers build."],
    get_h='The full <span class="accent">stack.</span>',
    get=[("Research", "Interviews, discovery workshops and usability testing."),
         ("UX", "User flows, wireframes and information architecture."),
         ("UI", "Custom branding, UI and data visualisation."),
         ("Design systems", "Custom UI components on proven libraries like Mantine and Ant Design.")],
    steps=[("Kick off", "Interviews"), ("Stage 1", "Research, UX & discovery workshops"), ("Stage 2", "Testing"), ("Stage 3", "UI design"), ("Launch", "Testing")],
    cases=["resultbook", "flowmo", "iseechange"],
    faq=[("Can you join our existing team?", "Yes. We work as an embedded part of your team or as a standalone design partner."),
         ("Which tools do you use?", "Figma for design, plus whatever your team uses for collaboration, research, analytics and project management."),
         ("Do you do user research?", "Yes. Research is where every project starts, from interviews to usability testing.")],
    related=["founding-mvp", "product-management", "ux-overhauls"]),

  dict(slug="product-management", group="How we lead", name="Product Management",
    title="Product management — MN Studio",
    meta="Roadmapping, prioritisation and discovery that keeps teams shipping the right things.",
    h1='Roadmaps that keep <span class="accent">teams shipping.</span>',
    lede="Roadmapping, prioritisation and discovery that keeps teams shipping the right things, in the right order.",
    problem_h='Clarity on what <span class="accent">to build next.</span>',
    problem=["A backlog full of good ideas isn't a strategy. Teams need a clear roadmap, a reason behind every priority, and someone who keeps discovery going while delivery continues.",
             "We run product management alongside design, so decisions are grounded in user research and the team always knows what matters most."],
    get_h='What we <span class="accent">own.</span>',
    get=[("Discovery", "Continuous research that feeds the roadmap."),
         ("Roadmapping", "A clear plan tied to business goals, not just a feature list."),
         ("Prioritisation", "Frameworks that make trade-offs visible and agreed."),
         ("Delivery", "Specs, stories and rituals in Jira, Linear or ClickUp that keep the team moving.")],
    steps=[("Understand", "Goals & users"), ("Discover", "Research & workshops"), ("Plan", "Roadmap & priorities"), ("Deliver", "With the team"), ("Learn", "Measure & repeat")],
    cases=["resultbook", "iseechange", "mentorship"],
    faq=[("Can you manage our engineering team?", "We run product management with your engineering leads: specs, prioritisation and rituals, while they own the technical delivery."),
         ("Do you replace a full-time PM?", "Often as an interim or fractional PM while you hire, and then we help onboard your new hire."),
         ("Which tools do you use?", "Jira, Linear, ClickUp, monday.com or Notion, whatever your team already uses.")],
    related=["leadership", "full-stack-design", "vc-private-equity"]),

  dict(slug="leadership", group="How we lead", name="Leadership",
    title="Design & product leadership — MN Studio",
    meta="Interim and fractional design and product leadership for startups and portfolio companies.",
    h1='Senior leadership, <span class="accent">when you need it.</span>',
    lede="Interim and fractional design and product leadership. A senior leader for your team, without the wait or cost of a full-time hire.",
    problem_h='Leadership gaps <span class="accent">slow everyone down.</span>',
    problem=["Without senior design and product leadership, teams lose direction: decisions stall, quality slips and good people get frustrated.",
             "We step in as your interim or fractional leader, set the direction, raise the bar, and build the team and process that will carry it forward."],
    get_h='What we <span class="accent">lead.</span>',
    get=[("Design leadership", "Direction, critique and quality across every product surface."),
         ("Product leadership", "Strategy, roadmap and alignment with founders and boards."),
         ("Team building", "Hiring, onboarding, workshops and team management."),
         ("Process", "Rituals and tools that help the team ship consistently.")],
    steps=[("Listen", "Team, product & goals"), ("Direct", "Vision & priorities"), ("Build", "Team & process"), ("Hand over", "To your permanent hire")],
    cases=["reunion", "resultbook", "flowmo"],
    faq=[("How much time do you spend with us?", "Fractional engagements are part-time and flex with your needs. We'll agree on a rhythm on the first call."),
         ("Can you help us hire?", "Yes. We help define the role, interview candidates and onboard your permanent leader."),
         ("Do you work with boards and investors?", "Yes. We regularly present design and product work to boards and incorporate their feedback.")],
    related=["product-management", "vc-private-equity", "full-stack-design"]),

  dict(slug="giving-back", group="Giving back", name="Giving back",
    title="Giving back — MN Studio",
    meta="One nonprofit design project every quarter, pro bono or at cost. Good design shouldn't only be for the highest bidder.",
    h1='For the missions <span class="accent">that matter.</span>',
    lede="One nonprofit design project every quarter, pro bono or at cost. Good design shouldn't only be for the highest bidder.",
    problem_h='Why we <span class="accent">give back.</span>',
    problem=["Some of the most important work in the world happens on the smallest budgets. Nonprofits and mission-driven teams deserve products as good as anyone's.",
             "Every quarter, we take on one nonprofit project for free or at cost, with the same team and standards as any other engagement."],
    get_h='How it <span class="accent">works.</span>',
    get=[("One per quarter", "We select one nonprofit project each quarter."),
         ("Pro bono or at cost", "Depending on the scope and the organisation's resources."),
         ("Same team, same care", "The work gets the same people and standards as any paid project."),
         ("Real outcomes", "A clear scope with a result you can launch and use.")],
    steps=[("Apply", "Email us"), ("Chat", "A short intro call"), ("Selection", "One project per quarter"), ("Design", "Scoped & delivered")],
    cases=["iseechange", "resultbook"],
    faq=[("Who can apply?", "Registered nonprofits and mission-driven organisations working on social or environmental impact."),
         ("What kind of projects fit?", "Websites, apps, internal tools, UX audits or a founding MVP, scoped so we can deliver it in about a quarter."),
         ("How do you choose?", "We look at the impact the project could have and whether design is the thing that will make the biggest difference.")],
    apply=True,
    related=["impact-startups", "founding-mvp", "ux-overhauls"]),
]
